// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNZe9ifx9ROZoye2O-61TBjpxgpoh5XZ0',
    appId: '1:825778679799:web:2b5bf081170cfb8ece08f2',
    messagingSenderId: '825778679799',
    projectId: 'foodappdatabase-a2583',
    authDomain: 'foodappdatabase-a2583.firebaseapp.com',
    storageBucket: 'foodappdatabase-a2583.firebasestorage.app',
    measurementId: 'G-4YGBPSK7W0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPgC8OVqYoD_o7hHRFZIskYNIFG3g5KvQ',
    appId: '1:825778679799:android:cbeddcc432f9c297ce08f2',
    messagingSenderId: '825778679799',
    projectId: 'foodappdatabase-a2583',
    storageBucket: 'foodappdatabase-a2583.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWf98xrD0HzYELb4FD_b7hJY1HoNFcWxk',
    appId: '1:825778679799:ios:1fc42d657d9ad78dce08f2',
    messagingSenderId: '825778679799',
    projectId: 'foodappdatabase-a2583',
    storageBucket: 'foodappdatabase-a2583.firebasestorage.app',
    iosClientId:
        '825778679799-rsqdg0nen7nt8b7c4bqh2bfrhlncstfc.apps.googleusercontent.com',
    iosBundleId: 'com.example.appDatDoAn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWf98xrD0HzYELb4FD_b7hJY1HoNFcWxk',
    appId: '1:825778679799:ios:1fc42d657d9ad78dce08f2',
    messagingSenderId: '825778679799',
    projectId: 'foodappdatabase-a2583',
    storageBucket: 'foodappdatabase-a2583.firebasestorage.app',
    iosClientId:
        '825778679799-rsqdg0nen7nt8b7c4bqh2bfrhlncstfc.apps.googleusercontent.com',
    iosBundleId: 'com.example.appDatDoAn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNZe9ifx9ROZoye2O-61TBjpxgpoh5XZ0',
    appId: '1:825778679799:web:bf2ee44a48a4aa79ce08f2',
    messagingSenderId: '825778679799',
    projectId: 'foodappdatabase-a2583',
    authDomain: 'foodappdatabase-a2583.firebaseapp.com',
    storageBucket: 'foodappdatabase-a2583.firebasestorage.app',
    measurementId: 'G-Y65L3P7SW8',
  );
}
